[package]
name = "typship"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
dialoguer = "0.11.0"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
toml = "0.8.19"
typst-syntax = "0.12.0"
url = "2.5.4"
whoami = "1.5.2"
