[package]
name = "typship"
version = "0.1.0"
edition = "2021"

[features]
default = []
git = ["git2"]

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
dialoguer = "0.11.0"
dirs = "5.0.1"
git2 = { version = "0.19.0", optional = true }
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
sha2 = "0.10.8"
toml = "0.8.19"
typst-kit = "0.12.0"
typst-syntax = "0.12.0"
url = "2.5.4"
whoami = "1.5.2"
