# This workflow publishes a package to the Typst Package Registry.
name: Publish Typst Package

on:
  workflow_dispatch:
    inputs:
      source:
        description: Source repository to publish the package
        required: true
        default: Myriad-Dreamin/packages
        type: string
      destination:
        description: Destination repository to publish the package
        required: true
        default: typst/packages
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Pull packages
        uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: ${{ inputs.source }}
          # Relative path under $GITHUB_WORKSPACE to place the repository
          path: "source"
      - name: List source files to publish
        run: |
          ls -lh tests/fixtures/example
      - name: List existing versions
        run: |
          ls -l source/packages/preview/example
      - name: Put package to @preview namespace
        run: |
          mv tests/fixtures/example source/packages/preview/example/0.1.1
      - name: Upload built typst.tmLanguage.json
        uses: actions/upload-artifact@v4
        with:
          name: preview-example-0.1.1
          path: source/packages/preview/example/0.1.1
      - name: Make branch to release
        run: |
          git config --global user.email "camiyoru@gmail.com"
          git config --global user.name "Myriad-Dreamin"
          git checkout -b preview/example/v0.1.1
          git add packages/preview/example/0.1.1
          git commit -m "build: bump @preview/example to 0.1.1"
          git push origin preview/example/v0.1.1
        working-directory: source
      - name: Make PR
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: source
          push-to-fork: ${{ inputs.destination }}
          commit-message: "build: bump @preview/example to 0.1.1"
          title: "build: bump @preview/example to 0.1.1"
          body: "This PR bumps @preview/example to 0.1.1"
          branch: "preview/example/v0.1.1"
          base: "main"
          reviewers: "Myriad-Dreamin"
          assignees: "Myriad-Dreamin"
          draft: false
